name: 'build and deploy production'

on:
  push:
    tags:
      - '*'

jobs:
  # 1. Job ใหม่เพื่อเตรียมชื่อ Image ที่เป็นตัวพิมพ์เล็ก
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.set-vars.outputs.image_name }}
    steps:
      - id: set-vars
        run: |
          # แปลงชื่อเจ้าของและชื่อ repo เป็นตัวพิมพ์เล็ก
          IMAGE_PATH="${GITHUB_REPOSITORY,,}"
          echo "image_name=$IMAGE_PATH" >> $GITHUB_OUTPUT

  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. เพิ่ม Step นี้เพื่อแปลงชื่อเป็นตัวพิมพ์เล็ก
      - name: Set lower case owner name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build image and push to GitHub Packages
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          # 2. เปลี่ยนมาใช้ตัวแปรที่เตรียมไว้
          image: ${{ env.IMAGE_NAME }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest,${{ github.ref_name }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    steps:
    - name: Set lower case owner name
      run: |
        echo "IMAGE_NAME_LOW=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.0
      env:
        CONTAINER_NAME: 'wisarut-vue-app'
      with:
        host: '167.172.92.228'
        username: 'root'
        password: 'se@2026NPRU'
        port: '22'
        # ส่งค่า IMAGE_NAME_LOW เข้าไปใน script
        envs: IMAGE_NAME_LOW, CONTAINER_NAME
        script: |
          # ใช้ตัวแปรที่ส่งมาจาก envs
          DOCKER_IMAGE_URL="ghcr.io/${IMAGE_NAME_LOW}:${{ github.ref_name }}"
          
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker rm -f $CONTAINER_NAME || true
          docker pull $DOCKER_IMAGE_URL
          docker run --restart=always -d --name $CONTAINER_NAME -p 8088:80 $DOCKER_IMAGE_URL